environments:
- name: lowers
  repository: prince.dkr.ecr.us-west-2.amazonaws.com
  excludefromshare: false
  source: ktrouble-utils
- name: uppers
  repository: journey.dkr.ecr.us-west-2.amazonaws.com
  excludefromshare: false
  source: ktrouble-utils
- name: cmaahs
  repository: us-docker.pkg.dev/cmaahs-repo
  excludefromshare: false
  source: ktrouble-utils
