environments:
- name: lowers
  repository: prince.dkr.ecr.us-west-2.amazonaws.com
  excludefromshare: false
  source: ktrouble-utils
  hidden: false
  removeupstream: false
- name: uppers
  repository: journey.dkr.ecr.us-west-2.amazonaws.com
  excludefromshare: false
  source: ktrouble-utils
  hidden: false
  removeupstream: false
- name: cjmaahs
  repository: us-docker.pkg.dev/cjmaahs-repo
  excludefromshare: false
  source: ktrouble-utils
  hidden: false
  removeupstream: false
