environments:
- name: lowers
  repository: us-docker.pkg.dev/my-lower-repo
  excludefromshare: false
  source: ktrouble-utils
  hidden: false
  removeupstream: false
- name: uppers
  repository: us-docker.pkg.dev/my-upper-repo
  excludefromshare: false
  source: ktrouble-utils
  hidden: false
  removeupstream: false
